---
- name: Установка Nginx
  become: true
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Создание директории для конфигов
  become: true
  file:
    path: /etc/nginx/conf.d
    state: directory
    mode: 0755

- name: Настройка проксирования
  become: true
  template:
    src: proxy.conf.j2
    dest: /etc/nginx/conf.d/proxy.conf
    validate: nginx -t -c %s

- name: Удаление дефолтной конфигурации
  become: true
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Проверка конфигурации Nginx
  become: true
  command: nginx -t
  register: nginx_test
  changed_when: false
  notify: Restart Nginx
